import { Readex_Pro } from 'next/font/google'

import Footer from "./components/Footer/Footer";
import Header from "./components/Header/Header";
import "./globals.css";

export const metadata = {
  title: "Momtaz - Home Page",
  description: "Generated by create next app",
};
const readex = Readex_Pro({
  subsets: ['latin']
})

export default function RootLayout({ children }) {
  return (
    <html lang="en" dir="rtl" className={readex.className}>
      <body className="min-h-screen flex flex-col">
        <Header />
        <main className="grow flex flex-col justify-center">
          {children}
        </main>
        <Footer />
      </body>
    </html>
  );
}
